### ISSUE TITLE
I would like help with this special 7-seg Display Module

### ISSUE THREAD

**Issue by ArcAIN6** [Andy4495/ICM7218#1]
As the subject line indicates, i have a rather special 7-Seg display module that has 4 digits, a time " : ", and 10 additional LEDs (5 top, and bottom)

I would like help with altering the library to use with this module. I'm currently using an ICM7228A in conjunction with an arduino pro-mini, but because of the oddities of the module, getting it to function correctly is a bit beyond my scope of knowledge. 

Any help would be much appreciated!!

**Additional Information:** 
As i don't have access to a datasheet (i've tried googling the part number **HXDF-4047BHG-01** printed on the side, but have had no luck)

I mapped out each pin to each LED, and have included an image that shows front and back image of the module, as well as an image depicting the pin-to-segment mapping, and polarity (it's common anode)

![unknown](https://user-images.githubusercontent.com/418929/185797306-6e3d4c4c-3b84-4ef6-885b-3fe70599d651.png)

**Comment by Andy4495** [comment]
I don’t have a setup to test this at the moment, but I think that since you were able to figure out the pinout of the LED, we should be able to get this to work. 

First, I want to confirm the wiring. I think that “Digit 1” of the ICM7228 refers to the left-most digit of the display. If not, it will be easy enough to tell and the digit connections can be easily switched.

From the ICM7228 perspective then, I would wire the four 7-segments as Digits 1 through 4 (left to right). Use Digit 5 to control the top row and digit separator (colon) LEDs. The bottom row would be wired as decimal points for digits 1-4. Digits 6, 7, 8 on the ICM7228 would be unused and not connected. To summarize: 

```text
ICM7228A        LED
1 		11	c
2 		8	e
3		12	b
4		10	DP
15 		1	Digit 1
16		2	Digit 2
17		3	Digit 5
18		NC	Digit 8
20		5	Digit 4
21		NC	Digit 7
22		NC	Digit 6
23		4	Digit 3
24		7	f
25		9	d
26		6	g
27		13	a
```

My library does not support the “Single Digit Update” mode of the ICM7228 (mainly because my particular project didn’t need it, so I never got around to implementing that). Every write to the display then needs to include data for all 5 digits at a time. It makes the programming a little more complicated, but it is still workable.

Since your display has both 7-segment digits and individually addressed segments, it is a little complicated to use HEXA or CODEB mode. So you probably will need to use DIRECT mode to control the display. 

For the first 4 digits, you can use the convertToSegments() method, and then individually figure out the correct bits to plug into the 5th digit of the array to control the top row/colon segments. In order to turn on the bottom row LEDs, just add periods (“.”) where you want them in the display string. 

For example: 

```cpp
char buffer[16];
myLED.setMode(ICM7218::DIRECT);
strncpy(buffer, "LED1", 15);  
buffer[4] = 0x58; // turn on left, middle, right of top row (segments a, c, e)
myLED.print(buffer);
```

To turn on one of the bottom LEDs (wired as decimal points), you would add a decimal to the string: 
`strncpy(buffer, "LED.1", 15);  
`

Note that this also increases the length of the string, so the buffer index for the individual LEDs would increase by 1: 
`buffer[5] = 0x58; // turn on left, middle, right of top row (segments a, c, e)
`

Look at my example sketch icm7218_test.ino, too. 

I hope that helps. Let me know if you have more questions. 

Andy

**Comment by ArcAIN6** [comment]
According to the datasheet for the ICM7228A,  the right-most digit would be
considered D1 (digit 1)

After wiring it as suggested, and running the test ino, there is activity
on the device, however, the entire bottom row never illuminates (pin 10 of
the module wired to DP of the ICM7228A)

As for figuring out how to map these pins / segments to the hex codes, i'm
completely at a loss there
[image: image.png]

**Comment by Andy4495** [comment]
OK, the ordering of the digits shouldn't matter that much for now. We'll just try to get the various segments of the display to work, and then you can tweak the code or the hardware connections to get the digits displayed in the correct order. 

Can you confirm that the pin numbers from the constructor match how you have the ICM7228 connected to your Arduino. 

Then, try this sketch (with the constructor updated as needed with correct pin numbers). This sketch displays something to every Digit and we should be able to see something happening in each area of the display. This code compiles, but I don't have a set up at the moment to test it. 

```cpp
#include <ICM7218.h>

// Constructor: Confirm/update these pin numbers match your Arduino->ICM7228 connection
// myLED(ID0, ID1, ID2, ID3, ID4, ID5, ID6, ID7, mode, write)
ICM7218 myLED(16, 3, 4, 5, 6, 7, 8, 9, 14, 15); // Update per your configuration

char convertBuffer[32];


void setup() {

  Serial.begin(9600);

}

void loop() {

  myLED.setMode(ICM7218::DIRECT);

  strncpy(convertBuffer, "1.2.3.4.5.6.7.8.", 16);
  Serial.println(convertBuffer);
  myLED.convertToSegments(convertBuffer);
  myLED.print(convertBuffer);
  delay(2000);

  strncpy(convertBuffer, "8.7.6.5.4.3.2.1.", 16);
  Serial.println(convertBuffer);
  myLED.convertToSegments(convertBuffer);
  myLED.print(convertBuffer);
  delay(2000);

  Serial.println("Turn on all decimal points (just the decimal points)");
  for (int i = 0; i < 8; i++) {
    convertBuffer[i] = 0x00; // Decimal point is reverse logic, so bit 7 == 0 means display decimal point
  }
  myLED.print(convertBuffer);
  delay(2000);

  Serial.println("Turn on a single segment in each Digit, starting with segment ‘a’, including decimal points.");
  convertBuffer[0] = 0x40; // Segment ‘a’
  convertBuffer[1] = 0x20; // Segment ‘b’
  convertBuffer[2] = 0x10; // Segment ‘c’
  convertBuffer[3] = 0x01; // Segment ‘d’
  convertBuffer[4] = 0x08; // Segment ‘e’
  convertBuffer[5] = 0x02; // Segment ‘f’
  convertBuffer[6] = 0x04; // Segment ‘g’
  convertBuffer[7] = 0x7f; // All 7 segments at the same time
  myLED.print(convertBuffer);
  delay(2000);

  Serial.println("Same thing, this time with segments in reverse order and no decimal points.");
  convertBuffer[0] = 0x84; // Segment ‘g’
  convertBuffer[1] = 0x82; // Segment ‘f’
  convertBuffer[2] = 0x88; // Segment ‘e’
  convertBuffer[3] = 0x81; // Segment ‘d’
  convertBuffer[4] = 0x90; // Segment ‘c’
  convertBuffer[5] = 0xa0; // Segment ‘b’
  convertBuffer[6] = 0xb0; // Segment ‘a’
  convertBuffer[7] = 0xff; // All 7 segments at the same time
  myLED.print(convertBuffer);
  delay(2000);

}
```


Look at Figure 11 and Table 6 in the ICM7228 data sheet to see how the individual data bits control individual LED segments. For example, to turn on the middle segment ("-"), you need to set the bit corresponding to "g" in the table. So, set bit ID2 which is 0x04. To turn on the segments needed to display the number 3, you would want bits a, b, c, d, g set which corresponds to ID6, ID5, ID4, ID2, ID0 -> 0x75. 

For the individual LEDs on the top row: take an example of the top left LED. It is connected to display pin 13. That is the same pin as segment "a" in the 7-segment display. So to turn that on, you would set the "a" bit (ID7) which corresponds to hex value 0x70. So sending a 0x70 to digit 5 would turn on the top left LED.

**Comment by ArcAIN6** [comment]
ok.. so... none of the arduino's i have access to have pins 14, 15 aand 16. the digital pins go 2 - 13

That being said, i just did digital pins 2 - 9 for ID0 - ID7,  pin 10 for mode, and pin 11 for write

i have the module connected as such:
Module Pin - ICM7228 Pin

5 - 15 - Digit 1
4 - 16 - Digit 2
2 - 23 - Digit 3
1 - 20 - Digit 4
3 - 17 - Digit 5
10 - 4 (bottom row LED's as DP)

13 - 27 - a
12 - 3 - b
11 -  1 - c
9 - 25 - d
8 - 2 - e
7 - 24 - f
6 - 26 - g

Here's a video of what's being displayed: 
[Video](https://cdn.discordapp.com/attachments/716336617425600524/1011069375874351185/20220821_202636.mp4)
https://cdn.discordapp.com/attachments/716336617425600524/1011069375874351185/20220821_202636.mp4

**Comment by ArcAIN6** [comment]
_

> `Look at Figure 11 and Table 6 in the ICM7228 data sheet to see how the individual data bits control individual LED segments. For example, to turn on the middle segment ("-"), you need to set the bit corresponding to "g" in the table. So, set bit ID2 which is 0x04. To turn on the segments needed to display the number 3, you would want bits a, b, c, d, g set which corresponds to ID6, ID5, ID4, ID2, ID0 -> 0x75.
> 
> For the individual LEDs on the top row: take an example of the top left LED. It is connected to display pin 13. That is the same pin as segment "a" in the 7-segment display. So to turn that on, you would set the "a" bit (ID7) which corresponds to hex value 0x70. So sending a 0x70 to digit 5 would turn on the top left LED.`

_

With this, the part that i guess i don't understand (yet) is the correlation between ID2 == 0x40 and ID7 == 0x70. it's probably something i should know, but i've not run into that before, and i feel it's probably something fundamentally easy to grasp once i know how / why the hex is derived

**Comment by Andy4495** [comment]
We are getting close... that video gives me some clues on what is happening. Some of the display is correct, some is incorrect. The problems point to a couple potential problems: 
1. Wiring issue
2. Library issue. 

I spotted one issue in my library that made one of the tests not work right (the "turn all decimal points on" test). There was also an error in one of the values I used in my test that made me think the wrong segments were lit when actually they were correct. 

I'd also like to confirm again that everything is wired correctly. There were a couple cases where the segments weren't quite displayed correctly (e.g. when displaying a 2, 4, or 5). Please check that the connections between the Arduino, the '7228 and the LED are as you described above. 

Also please confirm that this is the constructor you were using in the sketch when you took the video:  

```cpp
ICM7218 myLED(2,3,4,5,6,7,8,9,10,11); // Update per your configuration
```

Here is another test sketch, with updated tests that could help us figure out the remaining issues. It's getting a little late here tonight, but I'll work on it again on Monday once I hear back from you. I'll also dig out my old setup and make sure this test is working the way I would expect on one of my displays. 

```cpp
#include <ICM7218.h>

// Test 2

// Constructor: Confirm/update these pin numbers match your Arduino->ICM7228 connection
// myLED(ID0, ID1, ID2, ID3, ID4, ID5, ID6, ID7, mode, write)
ICM7218 myLED(2,3,4,5,6,7,8,9,10,11); // Update per your configuration

char convertBuffer[32];

void setup() {

  Serial.begin(9600);

}

void loop() {

  myLED.setMode(ICM7218::DIRECT);

  memset(convertBuffer, 0, 32);
  strncpy(convertBuffer, "1114.5.6.7.8.", 16);
  Serial.println(convertBuffer);
  myLED.convertToSegments(convertBuffer);
  myLED.print(convertBuffer);
  delay(2000);

  memset(convertBuffer, 0, 32);
  strncpy(convertBuffer, "8885.4.3.2.1.", 16);
  Serial.println(convertBuffer);
  myLED.convertToSegments(convertBuffer);
  myLED.print(convertBuffer);
  delay(2000);

  // The previous version of this check blanked the display, because the library handles all zeros a little differently
  Serial.println("Turn on all decimal points, turn on segment 'f'");
  for (int i = 0; i < 8; i++) {
    convertBuffer[i] = 0x02; // Decimal point is reverse logic, so bit 7 == 0 means display decimal point
  }
  myLED.print(convertBuffer);
  delay(2000);

  Serial.println("Turn off all decimal points, turn on segment 'e'");
  for (int i = 0; i < 8; i++) {
    convertBuffer[i] = 0x88; // Decimal point is reverse logic, so bit 7 == 0 means display decimal point
  }
  myLED.print(convertBuffer);
  delay(2000);

  Serial.println("Turn on a single segment in each Digit, starting with segment ‘a’, including decimal points.");
  convertBuffer[0] = 0x40; // Segment ‘a’
  convertBuffer[1] = 0x20; // Segment ‘b’
  convertBuffer[2] = 0x10; // Segment ‘c’
  convertBuffer[3] = 0x5c; // -- This is the top row and separator LEDs, display every other
  convertBuffer[4] = 0x08; // Segment ‘e’
  convertBuffer[5] = 0x02; // Segment ‘f’
  convertBuffer[6] = 0x04; // Segment ‘g’
  convertBuffer[7] = 0x7f; // All 7 segments at the same time
  myLED.print(convertBuffer);
  delay(2000);

  Serial.println("Same thing, this time with segments in reverse order and no decimal points.");
  convertBuffer[0] = 0x84; // Segment ‘g’
  convertBuffer[1] = 0x82; // Segment ‘f’
  convertBuffer[2] = 0x88; // Segment ‘e’
  convertBuffer[3] = 0x23; // -- This is the top row and separator LEDs. display the other ones
  convertBuffer[4] = 0x81; //  Segment 'd'
  convertBuffer[5] = 0x90; // Segment ‘c’
  convertBuffer[6] = 0xa0; // Segment ‘b’
  convertBuffer[7] = 0xc0; // Segment ‘a’
  myLED.print(convertBuffer);
  delay(2000);

}
```

For converting "ID2 = 0x40", the thing you need to learn is "converting from binary to hexadecimal". Each segment is represented by a binary digit in an 8-bit byte ID7-ID0 (7 segments plus the decimal point). I'm converting that 8-bit binary number to hexadecimal. There are tutorials on the web, this one from SparkFun might be useful: <https://learn.sparkfun.com/tutorials/hexadecimal>

There was also a typo in my previous explanation about this. When I was talking about the top left LED and segment "a", I should have said *the "a" bit (ID6) which corresponds to 0x40.* and ID7 would correspond to 0x80, not 0x70.

**Comment by ArcAIN6** [comment]
Yea, the breadboard i'm using is kind of on it's last leg, i need to get some new one's, so sometimes the pins need a little wiggle, or moved to a tighter hole. 

I can confirm the wiring from the nano to the ICM7228 is indeed
`ICM7218 myLED(2,3,4,5,6,7,8,9,10,11); 
,..................................`

As i'm getting ready for work, and don't really have time at this moment to unplug everything, and re-wire it all back up to be certain all pins are correct, i just threw the updated sketch in, and recorded another quick video so you can see the output: 

https://cdn.discordapp.com/attachments/716336617425600524/1011210523238469732/20220822_054746.mp4

I'll completely re-wire the entire thing when i get home from work later this evening, and run it again to see if anything's different, and i'll let you know the outcome. 

Also, this help is much appreciated, and i'm learning quite a lot from it!!!

**Comment by ArcAIN6** [comment]
Pulled all the LED wires, and re-inserted them just to make sure they were in the right positions (there might have been one or more out of position XD)

Updated Video:
 https://cdn.discordapp.com/attachments/716336617425600524/1011266707047854200/VID_20220822_093124.mp4

**Comment by Andy4495** [comment]
This last video after re-wiring helped a lot. I think I figured out a couple things now: 

- Segments e and f are switched. I think this is a wiring problem. 
  - Swap wires 7 and 8 on the LED
- Segments d and g are switched. I think this is a wiring problem.
  - Swap wires 6 and 9 on the LED
- To make the programming a little easier, shift the DIGITs so that the print strings match the order of the display. This way, the first element of the string array is the left-most digit, and the 5th element of the string array is the top row/separator LEDs: 
  - DIGIT1-7218 pin 15 not connected
  - DIGIT2-7218 pin 16 not connected
  - DIGIT3-7218 pin 23 not connected
  - DIGIT4-7218 pin 20 to LED pin 3 (top row/time separator)
  - DIGIT5-7218 pin 17 to LED pin 5
  - DIGIT6-7218 pin 22 to LED pin 4
  - DIGIT7-7218 pin 21 to LED pin 2
  - DIGIT8-7218 pin 18 to LED pin 1
- I think that my library method `convertToSegments()` does not properly handle the decimal point on the last digit (DIGIT1). However, by changing the wiring as above, that shouldn’t matter for your application because you won’t be using DIGIT1.

I’m hoping that fixes all the issues I am seeing in the videos. Here is an updated test sketch to try with the new wiring: 

```cpp
#include <ICM7218.h>

// Test 3

// Constructor: Confirm/update these pin numbers match your Arduino->ICM7228 connection
// myLED(ID0, ID1, ID2, ID3, ID4, ID5, ID6, ID7, mode, write)
ICM7218 myLED(2,3,4,5,6,7,8,9,10,11); // Update per your configuration

char convertBuffer[32];

void setup() {

  Serial.begin(9600);

}

void loop() {

  myLED.setMode(ICM7218::DIRECT);

  // Display 1234. All bottom LEDs lit (decimal points). Left 3 top LEDs lit (abc).
  memset(convertBuffer, 0, 32);
  strncpy(convertBuffer, "1.2.3.4.7.888", 16);
  Serial.println(convertBuffer);
  myLED.convertToSegments(convertBuffer);
  myLED.print(convertBuffer);
  delay(2000);

  // Display 5678. All bottom LEds lit (decimal points). All top LEDs (except 2nd) and both separator LEDs lit (acdefg).
  memset(convertBuffer, 0, 32);
  strncpy(convertBuffer, "5.6.7.8.9.000", 16);
  Serial.println(convertBuffer);
  myLED.convertToSegments(convertBuffer);
  myLED.print(convertBuffer);
  delay(2000);

  // Display 9090. Left 2 bottom LEDs lit (decimal points). 2nd and 3rd top LED and both separator LEDs lit (bcfg)
  memset(convertBuffer, 0, 32);
  strncpy(convertBuffer, "9.0.904444", 16);
  Serial.println(convertBuffer);
  myLED.convertToSegments(convertBuffer);
  myLED.print(convertBuffer);
  delay(2000);

  // A previous version of this check blanked the display, because the library handles all zeros a little differently
  Serial.println("Turn on all decimal points, turn on segment 'f'");
  for (int i = 0; i < 8; i++) {
    convertBuffer[i] = 0x02; // Decimal point is reverse logic, so bit 7 == 0 means display decimal point
  }
  myLED.print(convertBuffer);
  delay(2000);

  Serial.println("Turn off all decimal points, turn on segment 'd'");
  for (int i = 0; i < 8; i++) {
    convertBuffer[i] = 0x81; // Decimal point is reverse logic, so bit 7 == 0 means display decimal point
  }
  myLED.print(convertBuffer);
  delay(2000);

  Serial.println("Turn on a single segment in each Digit, starting with segment ‘a’, including decimal points.");
  convertBuffer[0] = 0x40; // Segment ‘a’
  convertBuffer[1] = 0x20; // Segment ‘b’
  convertBuffer[2] = 0x10; // Segment ‘c’
  convertBuffer[3] = 0x01; // Segment 'd'
  convertBuffer[4] = 0x5c; // -- This is the top row and separator LEDs, display every other LED
  myLED.print(convertBuffer);
  delay(2000);

  Serial.println("Same thing, this time with segments in reverse order and no decimal points.");
  convertBuffer[0] = 0x88; // Segment ‘e’ and turn off decimal point (bit 7 high)
  convertBuffer[1] = 0x82; // Segment ‘f’ and turn off decimal point (bit 7 high)
  convertBuffer[2] = 0x84; // Segment ‘g’ and turn off decimal point (bit 7 high)
  convertBuffer[3] = 0xff; // All segments and turn off decimal point (bit 7 high)
  convertBuffer[4] = 0xA3; // -- This is the top row and separator LEDs. display the ones that were off in previous test
  myLED.print(convertBuffer);
  delay(2000);

}
```

**Comment by ArcAIN6** [comment]
oooooo much better
EDITED: Wrong video initially linked: 
https://cdn.discordapp.com/attachments/716336617425600524/1011299593826357359/VID_20220822_111641.mp4

**Comment by Andy4495** [comment]
Great! The display is now showing exactly what I expect for each of the tests in my sketch. A couple of the comments in my sketch are incorrect, see below for the same program but with corrected comments.

Now that the hardware and software are working, I guess the next question is, do you understand how my example sketch works, and are you able to program the display yourself now? 

```cpp
#include <ICM7218.h>

// Test 4

// Constructor: Confirm/update these pin numbers match your Arduino->ICM7228 connection
// myLED(ID0, ID1, ID2, ID3, ID4, ID5, ID6, ID7, mode, write)
ICM7218 myLED(2,3,4,5,6,7,8,9,10,11); // Update per your configuration

char convertBuffer[32];

void setup() {

  Serial.begin(9600);
  Serial.println("ICM7228 Test 4");

}

void loop() {

  myLED.setMode(ICM7218::DIRECT);

  // Display 1234. All bottom LEDs lit (decimal points). Left 3 top LEDs lit (abc).
  memset(convertBuffer, 0, 32);
  strncpy(convertBuffer, "1.2.3.4.7.888", 16);
  Serial.println(convertBuffer);
  myLED.convertToSegments(convertBuffer);
  myLED.print(convertBuffer);
  delay(2000);

  // Display 5678. All bottom LEds lit (decimal points). All top LEDs (except 5th) and both separator LEDs lit (abcdfg).
  memset(convertBuffer, 0, 32);
  strncpy(convertBuffer, "5.6.7.8.9.000", 16);
  Serial.println(convertBuffer);
  myLED.convertToSegments(convertBuffer);
  myLED.print(convertBuffer);
  delay(2000);

  // Display 9090. Left 2 bottom LEDs lit (decimal points). 2nd and 3rd top LED and both separator LEDs lit (bcfg)
  memset(convertBuffer, 0, 32);
  strncpy(convertBuffer, "9.0.904444", 16);
  Serial.println(convertBuffer);
  myLED.convertToSegments(convertBuffer);
  myLED.print(convertBuffer);
  delay(2000);

  // All decimal points (bottom row) and segment f (including the top dot in the time separator)
  Serial.println("Turn on all decimal points, turn on segment 'f'");
  for (int i = 0; i < 8; i++) {
    convertBuffer[i] = 0x02; // Decimal point is reverse logic, so bit 7 == 0 means display decimal point
  }
  myLED.print(convertBuffer);
  delay(2000);

  // No decimal points (bottom row off), turn on segment d (including 4th led on top row)
  Serial.println("Turn off all decimal points, turn on segment 'd'");
  for (int i = 0; i < 8; i++) {
    convertBuffer[i] = 0x81; // Decimal point is reverse logic, so bit 7 == 0 means display decimal point
  }
  myLED.print(convertBuffer);
  delay(2000);

  // Turn on segment a, b, c, d individually, plus every other top row and separator LED. All bottom row turn on.
  Serial.println("Turn on a single segment in each Digit, starting with segment ‘a’, including decimal points.");
  convertBuffer[0] = 0x40; // Segment ‘a’
  convertBuffer[1] = 0x20; // Segment ‘b’
  convertBuffer[2] = 0x10; // Segment ‘c’
  convertBuffer[3] = 0x01; // Segment 'd'
  convertBuffer[4] = 0x5c; // -- This is the top row and separator LEDs, display every other LED
  myLED.print(convertBuffer);
  delay(2000);

  // Turn on segment e, f, g individually, then all segments (number "8") in last digit. Every other top row/separator (opposite of previous test), bottom row off
  Serial.println("Segments e, f, g, all, opposite top/separator LEDs from previous test, no decimal points.");
  convertBuffer[0] = 0x88; // Segment ‘e’ and turn off decimal point (bit 7 high)
  convertBuffer[1] = 0x82; // Segment ‘f’ and turn off decimal point (bit 7 high)
  convertBuffer[2] = 0x84; // Segment ‘g’ and turn off decimal point (bit 7 high)
  convertBuffer[3] = 0xff; // All segments and turn off decimal point (bit 7 high)
  convertBuffer[4] = 0xA3; // -- This is the top row and separator LEDs. display the ones that were off in previous test
  myLED.print(convertBuffer);
  delay(2000);

}
```

**Comment by ArcAIN6** [comment]
ty ty for the help :)
